### ISSUE TITLE
sequence numbers not updated in indexes?

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/edv-client#17] opened 2019-12-16 16:32 UTC
Version: 2.0.1-0

I would expect this to pass, but it does not:

```
it("sequence numbers from updates are reflected in indexes", async () => {
    const { keyAgreementKey, hmac } = mock.keys;
    let docs = [];
    const config = await EdvClient.createEdv({
      config: {
        sequence: 0,
        controller: mock.accountId,
        keyAgreementKey: { id: keyAgreementKey.id, type: keyAgreementKey.type },
        hmac: { id: hmac.id, type: hmac.type },
        referenceId: "web"
      }
    });
    const client = new EdvClient({ id: config.id, keyAgreementKey, hmac });
    client.ensureIndex({ attribute: "content.indexedKey" });
    const testId = await EdvClient.generateId();
    const doc = {
      id: testId,
      content: { someKey: "someValue", indexedKey: "value1" }
    };
    const version1 = await client.insert({
      doc,
      invocationSigner,
      keyResolver
    });
    version1.content = { someKey: "aNewValue" };
    await client.update({ doc: version1, invocationSigner, keyResolver });
    const version2 = await client.get({ id: doc.id, invocationSigner });
    docs = await client.find({
      has: "content.indexedKey",
      invocationSigner
    });
    version2.indexed[0].sequence.should.equal(docs[0].sequence);
  });
```

**Comment by OR13** [comment] 2019-12-16 16:33
I am looking for a way to get the latest version of all docs by an index value.

**Comment by OR13** [comment] 2019-12-16 16:36
Work arround is to first get the index, then reduce by id, and then get the doc directly:

```
const docsFromGet = await Promise.all(
      docs.map(d => {
        return client.get({ id: d.id, invocationSigner });
      })
    );
```

**Comment by OR13** [comment] 2019-12-16 16:46
possible i'm not interpreting the concept of sequence number correctly...

**Comment by aljones15** [comment] 2019-12-16 16:55
Are you sure this is running on a real mongo database? I believe some of these tests use sinon stubs: https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js

So the sequence not being incremented is probably due to the test framework not incrementing it.

**Comment by OR13** [comment] 2019-12-16 17:48
I am not running this in mongo, I'm using the stubs, since they are pretty much the source of truth for integration (I have database adapters for a real working version, but their behavior is defined according to the behavior of the stubs).

I treat the data returned from the edv-client tests as the source of truth for behavior of our server implementation.

**Comment by OR13** [comment] 2019-12-16 18:15
The test I provided in probably not as helpful as this one:
```

  it("indexed updates work as expected", async () => {
    const getLatestDocsByIndexHas = async (client, invocationSigner, index) => {
      const indexedDocs = await client.find({
        has: index,
        invocationSigner
      });
      const uniqueIds = [...new Set(indexedDocs.map(item => item.id))];

      const docsFromGet = await Promise.all(
        uniqueIds.map(id => {
          return client.get({ id, invocationSigner });
        })
      );
      return docsFromGet;
    };

    const client = await mock.createEdv();
    client.ensureIndex({ attribute: "content.indexedKey" });
    const testId = await EdvClient.generateId();
    const doc = {
      id: testId,
      content: { someKey: "111111", indexedKey: "value1" }
    };
    let version1 = await client.insert({
      doc,
      invocationSigner,
      keyResolver
    });
    version1 = await client.get({ id: doc.id, invocationSigner });

    // console.log("version: 1", version1);
    await client.update({
      doc: {
        ...version1,
        content: {
          ...version1.content,
          someKey: "22222"
        }
      },
      invocationSigner,
      keyResolver
    });
    const version2 = await client.get({ id: doc.id, invocationSigner });
    // console.log("version: 2", version2);
    await client.update({
      doc: {
        ...version2,
        content: {
          ...version2.content,
          someKey: "33333"
        }
      },
      invocationSigner,
      keyResolver
    });
    const version3 = await client.get({ id: doc.id, invocationSigner });
    // console.log("version: 3", version3);

    let docs = await client.find({
      has: "content.indexedKey",
      invocationSigner
    });

    // console.log(docs);

    const docsFromGet = await getLatestDocsByIndexHas(
      client,
      invocationSigner,
      "content.indexedKey"
    );

    console.log("docsFromGet: ", docsFromGet);
  });
```

Here we see 3 document updates, and the sequence numbers do in fact increment. However, I need to use get on the id to get the latest documents by index.

This could be expected behavior, feel free to close.

**Comment by aljones15** [comment] 2019-12-16 18:39
@OR13 I think you might have found a small bug in the stubs so my apologies. I am able to replicate so I will look into it for a moment today provided what you're testing for is expected behavior. @dlongley is orie's test correct?

**Comment by OR13** [comment] 2019-12-16 21:14
I can get the docs by index, but i get all versions of them, not just the latest one.

This might be expected behavior, and the workaround I have works for now, but I will need to update my edv server implementation if find by index is supposed to only return all documents that match the index with latest sequence number.

**Comment by dlongley** [comment] 2019-12-16 22:02
@aljones15, I suspect that the mock storage doesn't clear documents from existing indexes when the attributes that were previously indexed are removed in a subsequent update. So when a document update comes in, the mock storage should remove that document (based on its `id`) from any indexes and then add it back in to any indexes that still apply per the update.

**Comment by OR13** [comment] 2019-12-16 22:55
In my app tests, I was also assuming that the server would increment sequence numbers... they need to be provided... this may be a bit confusing for developers who think that `id` and `content` are all that are needed for updated to be managed... without providing a sequence number, your updates will always appear to be sequence 0.

**Comment by aljones15** [comment] 2019-12-17 14:08
> In my app tests, I was also assuming that the server would increment sequence numbers... they need to be provided... this may be a bit confusing for developers who think that `id` and `content` are all that are needed for updated to be managed... without providing a sequence number, your updates will always appear to be sequence 0.
> 
> this again could be expected behavior, but I was confused by it at first.

The behavior I would expect would be:

1. Reject the update if the sequence number does not match the current sequence (i.e. the update was made with an older version of the document).
2. server auto-increments the document.

Anyways, the logic to update the index is there, but it looks like it's not firing for some reason. Sorry about the delay on this one, it's the holidays and my mom has this incredibly ability to interrupt me the second I get to work.

**Comment by dlongley** [comment] 2019-12-17 15:06
The server is not responsible for incrementing sequence numbers, the client is. However, the server *is* responsible for rejecting out-of-order sequence numbers on insert/update.

**Comment by aljones15** [comment] 2019-12-17 16:53
@OR13 ok so the bug is the updated document's indexed property has no attributes. Looking into it.

**Comment by aljones15** [comment] 2019-12-17 21:35
@OR13 PR for this bug is here: https://github.com/digitalbazaar/edv-client/pull/18

I added both of the tests from this issue so there is a check we don't revert in terms of behavior. Sorry about how long this took. Let me know if that PR fixes it on your side.

**Comment by OR13** [comment] 2019-12-17 22:23
My side is built from your side :) Whatever behavior you support I will adjust my implementation to match. It looks like your PR resolves the issue, I left some comments.

**Comment by aljones15** [comment] 2020-01-27 15:51
@OR13 just to make sure it is ok to close this issue? Looks PR resolved issued so I'm closing this and moving on to other issues.

**Closed by aljones15** 2020-01-27 15:51 UTC
Labels: invalid
